import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.22'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-script-runtime"
}

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions.jvmTarget = "17"
}
