import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id 'application'
    id 'org.jetbrains.kotlin.jvm' version '1.7.10'
}

repositories {
    mavenCentral()
}

mainClassName = 'javafx.example.AppKt'

tasks.withType(KotlinCompile).configureEach {
    kotlinOptions.jvmTarget = "17"
}
